/*
###############################################################
#  Generated by:      Cadence Innovus 15.23-s045_1
#  OS:                Linux x86_64(Host ID ieng6-ece-20.ucsd.edu)
#  Generated on:      Sat Mar 22 19:29:23 2025
#  Design:            fullchip
#  Command:           saveNetlist fullchip.pnr.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Ultra(TM) in wire load mode
// Version   : K-2015.06-SP2
// Date      : Thu Mar 20 18:17:10 2025
/////////////////////////////////////////////////////////////
module fullchip (
	clk, 
	mem_in1, 
	mem_in2, 
	inst1, 
	inst2, 
	reset, 
	out1, 
	out2);
   input clk;
   input [127:0] mem_in1;
   input [127:0] mem_in2;
   input [18:0] inst1;
   input [18:0] inst2;
   input reset;
   output [159:0] out1;
   output [159:0] out2;

   // Internal wires
   wire CTS_8;
   wire CTS_7;
   wire FE_OFN429_out1_44_;
   wire FE_OFN427_out2_125_;
   wire FE_OFN425_out1_109_;
   wire FE_OFN423_out1_124_;
   wire FE_OFN420_sum_out1_0_;
   wire FE_OFN419_sum_out1_0_;
   wire FE_OFN418_sum_out1_1_;
   wire FE_OFN417_sum_out1_1_;
   wire FE_OFN416_sum_out1_2_;
   wire FE_OFN415_sum_out1_2_;
   wire FE_OFN414_sum_out1_3_;
   wire FE_OFN413_sum_out1_3_;
   wire FE_OFN412_sum_out1_4_;
   wire FE_OFN411_sum_out1_4_;
   wire FE_OFN410_sum_out1_5_;
   wire FE_OFN409_sum_out1_5_;
   wire FE_OFN408_sum_out1_6_;
   wire FE_OFN407_sum_out1_6_;
   wire FE_OFN406_sum_out1_7_;
   wire FE_OFN405_sum_out1_7_;
   wire FE_OFN404_sum_out1_8_;
   wire FE_OFN403_sum_out1_8_;
   wire FE_OFN402_sum_out1_9_;
   wire FE_OFN401_sum_out1_9_;
   wire FE_OFN400_sum_out1_10_;
   wire FE_OFN399_sum_out1_10_;
   wire FE_OFN398_sum_out1_11_;
   wire FE_OFN397_sum_out1_11_;
   wire FE_OFN396_sum_out1_12_;
   wire FE_OFN395_sum_out1_12_;
   wire FE_OFN394_sum_out1_13_;
   wire FE_OFN393_sum_out1_13_;
   wire FE_OFN392_sum_out1_14_;
   wire FE_OFN391_sum_out1_14_;
   wire FE_OFN390_sum_out1_15_;
   wire FE_OFN389_sum_out1_15_;
   wire FE_OFN388_sum_out1_16_;
   wire FE_OFN387_sum_out1_16_;
   wire FE_OFN386_sum_out1_17_;
   wire FE_OFN385_sum_out1_17_;
   wire FE_OFN384_sum_out1_18_;
   wire FE_OFN383_sum_out1_18_;
   wire FE_OFN382_sum_out1_19_;
   wire FE_OFN381_sum_out1_19_;
   wire FE_OFN380_sum_out1_20_;
   wire FE_OFN379_sum_out1_20_;
   wire FE_OFN378_sum_out1_21_;
   wire FE_OFN377_sum_out1_21_;
   wire FE_OFN376_sum_out1_22_;
   wire FE_OFN375_sum_out1_22_;
   wire FE_OFN374_sum_out1_22_;
   wire FE_OFN373_sum_out1_23_;
   wire FE_OFN372_sum_out1_23_;
   wire FE_OFN371_sum_out2_0_;
   wire FE_OFN370_sum_out2_0_;
   wire FE_OFN369_sum_out2_1_;
   wire FE_OFN368_sum_out2_1_;
   wire FE_OFN367_sum_out2_2_;
   wire FE_OFN366_sum_out2_2_;
   wire FE_OFN365_sum_out2_3_;
   wire FE_OFN364_sum_out2_3_;
   wire FE_OFN363_sum_out2_4_;
   wire FE_OFN362_sum_out2_4_;
   wire FE_OFN361_sum_out2_5_;
   wire FE_OFN360_sum_out2_5_;
   wire FE_OFN359_sum_out2_6_;
   wire FE_OFN358_sum_out2_6_;
   wire FE_OFN357_sum_out2_7_;
   wire FE_OFN356_sum_out2_7_;
   wire FE_OFN355_sum_out2_8_;
   wire FE_OFN354_sum_out2_8_;
   wire FE_OFN353_sum_out2_9_;
   wire FE_OFN352_sum_out2_9_;
   wire FE_OFN351_sum_out2_10_;
   wire FE_OFN350_sum_out2_10_;
   wire FE_OFN349_sum_out2_11_;
   wire FE_OFN348_sum_out2_11_;
   wire FE_OFN347_sum_out2_12_;
   wire FE_OFN346_sum_out2_12_;
   wire FE_OFN345_sum_out2_13_;
   wire FE_OFN344_sum_out2_13_;
   wire FE_OFN343_sum_out2_14_;
   wire FE_OFN342_sum_out2_14_;
   wire FE_OFN341_sum_out2_15_;
   wire FE_OFN340_sum_out2_15_;
   wire FE_OFN339_sum_out2_16_;
   wire FE_OFN338_sum_out2_16_;
   wire FE_OFN337_sum_out2_17_;
   wire FE_OFN336_sum_out2_17_;
   wire FE_OFN335_sum_out2_18_;
   wire FE_OFN334_sum_out2_18_;
   wire FE_OFN333_sum_out2_19_;
   wire FE_OFN332_sum_out2_19_;
   wire FE_OFN331_sum_out2_20_;
   wire FE_OFN330_sum_out2_20_;
   wire FE_OFN329_sum_out2_21_;
   wire FE_OFN328_sum_out2_21_;
   wire FE_OFN327_sum_out2_22_;
   wire FE_OFN326_sum_out2_22_;
   wire FE_OFN325_sum_out2_23_;
   wire FE_OFN324_sum_out2_23_;
   wire FE_OFN322_out2_0_;
   wire FE_OFN320_out2_1_;
   wire FE_OFN318_out2_2_;
   wire FE_OFN316_out2_3_;
   wire FE_OFN314_out2_4_;
   wire FE_OFN312_out2_5_;
   wire FE_OFN310_out2_6_;
   wire FE_OFN308_out2_7_;
   wire FE_OFN306_out2_8_;
   wire FE_OFN304_out2_9_;
   wire FE_OFN302_out2_10_;
   wire FE_OFN300_out2_11_;
   wire FE_OFN298_out2_12_;
   wire FE_OFN296_out2_13_;
   wire FE_OFN294_out2_14_;
   wire FE_OFN292_out2_15_;
   wire FE_OFN290_out2_16_;
   wire FE_OFN288_out2_17_;
   wire FE_OFN286_out2_18_;
   wire FE_OFN284_out2_19_;
   wire FE_OFN282_out2_20_;
   wire FE_OFN280_out2_21_;
   wire FE_OFN278_out2_22_;
   wire FE_OFN276_out2_23_;
   wire FE_OFN274_out2_24_;
   wire FE_OFN272_out2_25_;
   wire FE_OFN270_out2_26_;
   wire FE_OFN268_out2_27_;
   wire FE_OFN266_out2_28_;
   wire FE_OFN264_out2_29_;
   wire FE_OFN262_out2_30_;
   wire FE_OFN260_out2_31_;
   wire FE_OFN258_out2_32_;
   wire FE_OFN256_out2_33_;
   wire FE_OFN254_out2_34_;
   wire FE_OFN252_out2_35_;
   wire FE_OFN250_out2_36_;
   wire FE_OFN248_out2_37_;
   wire FE_OFN246_out2_38_;
   wire FE_OFN244_out2_39_;
   wire FE_OFN242_out2_40_;
   wire FE_OFN240_out2_41_;
   wire FE_OFN238_out2_42_;
   wire FE_OFN236_out2_43_;
   wire FE_OFN234_out2_44_;
   wire FE_OFN232_out2_45_;
   wire FE_OFN230_out2_46_;
   wire FE_OFN228_out2_47_;
   wire FE_OFN226_out2_48_;
   wire FE_OFN224_out2_49_;
   wire FE_OFN222_out2_50_;
   wire FE_OFN220_out2_51_;
   wire FE_OFN218_out2_52_;
   wire FE_OFN216_out2_53_;
   wire FE_OFN214_out2_54_;
   wire FE_OFN212_out2_55_;
   wire FE_OFN210_out2_56_;
   wire FE_OFN208_out2_57_;
   wire FE_OFN206_out2_58_;
   wire FE_OFN204_out2_59_;
   wire FE_OFN202_out2_60_;
   wire FE_OFN200_out2_61_;
   wire FE_OFN198_out2_62_;
   wire FE_OFN196_out2_63_;
   wire FE_OFN194_out2_64_;
   wire FE_OFN192_out2_65_;
   wire FE_OFN190_out2_66_;
   wire FE_OFN188_out2_67_;
   wire FE_OFN186_out2_68_;
   wire FE_OFN184_out2_69_;
   wire FE_OFN182_out2_70_;
   wire FE_OFN180_out2_71_;
   wire FE_OFN178_out2_72_;
   wire FE_OFN176_out2_73_;
   wire FE_OFN174_out2_74_;
   wire FE_OFN172_out2_75_;
   wire FE_OFN170_out2_76_;
   wire FE_OFN168_out2_77_;
   wire FE_OFN166_out2_78_;
   wire FE_OFN164_out2_79_;
   wire FE_OFN162_out2_80_;
   wire FE_OFN160_out2_81_;
   wire FE_OFN158_out2_83_;
   wire FE_OFN156_out2_84_;
   wire FE_OFN154_out2_85_;
   wire FE_OFN152_out2_87_;
   wire FE_OFN150_out2_89_;
   wire FE_OFN148_out2_126_;
   wire FE_OFN146_out1_0_;
   wire FE_OFN144_out1_1_;
   wire FE_OFN142_out1_2_;
   wire FE_OFN140_out1_3_;
   wire FE_OFN138_out1_4_;
   wire FE_OFN136_out1_5_;
   wire FE_OFN134_out1_6_;
   wire FE_OFN132_out1_7_;
   wire FE_OFN130_out1_8_;
   wire FE_OFN128_out1_9_;
   wire FE_OFN126_out1_10_;
   wire FE_OFN124_out1_11_;
   wire FE_OFN122_out1_12_;
   wire FE_OFN120_out1_13_;
   wire FE_OFN118_out1_14_;
   wire FE_OFN116_out1_15_;
   wire FE_OFN114_out1_16_;
   wire FE_OFN112_out1_17_;
   wire FE_OFN110_out1_18_;
   wire FE_OFN108_out1_19_;
   wire FE_OFN106_out1_20_;
   wire FE_OFN104_out1_21_;
   wire FE_OFN102_out1_22_;
   wire FE_OFN100_out1_23_;
   wire FE_OFN98_out1_24_;
   wire FE_OFN96_out1_25_;
   wire FE_OFN94_out1_26_;
   wire FE_OFN92_out1_27_;
   wire FE_OFN90_out1_28_;
   wire FE_OFN88_out1_31_;
   wire FE_OFN86_out1_32_;
   wire FE_OFN84_out1_39_;
   wire FE_OFN82_out1_40_;
   wire FE_OFN80_out1_43_;
   wire FE_OFN78_out1_45_;
   wire FE_OFN76_out1_46_;
   wire FE_OFN74_out1_48_;
   wire FE_OFN72_out1_51_;
   wire FE_OFN70_out1_56_;
   wire FE_OFN68_out1_64_;
   wire FE_OFN66_out1_65_;
   wire FE_OFN64_out1_66_;
   wire FE_OFN62_out1_67_;
   wire FE_OFN60_out1_68_;
   wire FE_OFN58_out1_70_;
   wire FE_OFN56_out1_76_;
   wire FE_OFN54_out1_77_;
   wire FE_OFN52_out1_78_;
   wire FE_OFN50_out1_79_;
   wire FE_OFN48_out1_80_;
   wire FE_OFN46_out1_81_;
   wire FE_OFN44_out1_83_;
   wire FE_OFN42_out1_84_;
   wire FE_OFN40_out1_87_;
   wire FE_OFN38_out1_89_;
   wire FE_OFN36_out1_90_;
   wire FE_OFN34_out1_91_;
   wire FE_OFN32_out1_92_;
   wire FE_OFN30_out1_93_;
   wire FE_OFN28_out1_94_;
   wire FE_OFN26_out1_95_;
   wire FE_OFN24_out1_96_;
   wire FE_OFN22_out1_97_;
   wire FE_OFN20_out1_98_;
   wire FE_OFN18_out1_99_;
   wire FE_OFN16_out1_100_;
   wire FE_OFN14_out1_101_;
   wire FE_OFN12_out1_106_;
   wire FE_OFN10_out1_112_;
   wire FE_OFN8_out1_125_;
   wire FE_OFN6_out1_126_;
   wire FE_OFN4_out1_127_;
   wire FE_OFN3_inst2_18_;
   wire FE_OFN2_inst2_18_;
   wire FE_OFN1_inst1_18_;
   wire FE_OFN0_inst1_18_;
   wire [23:0] sum_out2;
   wire [23:0] sum_out1;

   CKBD16 CTS_ccl_BUF_clk_G0_L1_2 (.I(clk),
	.Z(CTS_8));
   CKBD16 CTS_ccl_BUF_clk_G0_L1_1 (.I(clk),
	.Z(CTS_7));
   CKBD0 FE_OFC430_out1_44_ (.I(FE_OFN429_out1_44_),
	.Z(out1[44]));
   CKBD0 FE_OFC428_out2_125_ (.I(FE_OFN427_out2_125_),
	.Z(out2[125]));
   CKBD0 FE_OFC426_out1_109_ (.I(FE_OFN425_out1_109_),
	.Z(out1[109]));
   CKBD0 FE_OFC424_out1_124_ (.I(FE_OFN423_out1_124_),
	.Z(out1[124]));
   CKND3 FE_OFC420_sum_out1_0_ (.I(FE_OFN419_sum_out1_0_),
	.ZN(FE_OFN420_sum_out1_0_));
   CKND3 FE_OFC419_sum_out1_0_ (.I(sum_out1[0]),
	.ZN(FE_OFN419_sum_out1_0_));
   CKND3 FE_OFC418_sum_out1_1_ (.I(FE_OFN417_sum_out1_1_),
	.ZN(FE_OFN418_sum_out1_1_));
   CKND3 FE_OFC417_sum_out1_1_ (.I(sum_out1[1]),
	.ZN(FE_OFN417_sum_out1_1_));
   CKND3 FE_OFC416_sum_out1_2_ (.I(FE_OFN415_sum_out1_2_),
	.ZN(FE_OFN416_sum_out1_2_));
   CKND3 FE_OFC415_sum_out1_2_ (.I(sum_out1[2]),
	.ZN(FE_OFN415_sum_out1_2_));
   CKND3 FE_OFC414_sum_out1_3_ (.I(FE_OFN413_sum_out1_3_),
	.ZN(FE_OFN414_sum_out1_3_));
   CKND3 FE_OFC413_sum_out1_3_ (.I(sum_out1[3]),
	.ZN(FE_OFN413_sum_out1_3_));
   CKND3 FE_OFC412_sum_out1_4_ (.I(FE_OFN411_sum_out1_4_),
	.ZN(FE_OFN412_sum_out1_4_));
   CKND3 FE_OFC411_sum_out1_4_ (.I(sum_out1[4]),
	.ZN(FE_OFN411_sum_out1_4_));
   CKND3 FE_OFC410_sum_out1_5_ (.I(FE_OFN409_sum_out1_5_),
	.ZN(FE_OFN410_sum_out1_5_));
   CKND3 FE_OFC409_sum_out1_5_ (.I(sum_out1[5]),
	.ZN(FE_OFN409_sum_out1_5_));
   CKND3 FE_OFC408_sum_out1_6_ (.I(FE_OFN407_sum_out1_6_),
	.ZN(FE_OFN408_sum_out1_6_));
   CKND3 FE_OFC407_sum_out1_6_ (.I(sum_out1[6]),
	.ZN(FE_OFN407_sum_out1_6_));
   CKND3 FE_OFC406_sum_out1_7_ (.I(FE_OFN405_sum_out1_7_),
	.ZN(FE_OFN406_sum_out1_7_));
   CKND3 FE_OFC405_sum_out1_7_ (.I(sum_out1[7]),
	.ZN(FE_OFN405_sum_out1_7_));
   CKND3 FE_OFC404_sum_out1_8_ (.I(FE_OFN403_sum_out1_8_),
	.ZN(FE_OFN404_sum_out1_8_));
   CKND3 FE_OFC403_sum_out1_8_ (.I(sum_out1[8]),
	.ZN(FE_OFN403_sum_out1_8_));
   CKND3 FE_OFC402_sum_out1_9_ (.I(FE_OFN401_sum_out1_9_),
	.ZN(FE_OFN402_sum_out1_9_));
   CKND3 FE_OFC401_sum_out1_9_ (.I(sum_out1[9]),
	.ZN(FE_OFN401_sum_out1_9_));
   CKND3 FE_OFC400_sum_out1_10_ (.I(FE_OFN399_sum_out1_10_),
	.ZN(FE_OFN400_sum_out1_10_));
   CKND3 FE_OFC399_sum_out1_10_ (.I(sum_out1[10]),
	.ZN(FE_OFN399_sum_out1_10_));
   CKND3 FE_OFC398_sum_out1_11_ (.I(FE_OFN397_sum_out1_11_),
	.ZN(FE_OFN398_sum_out1_11_));
   CKND3 FE_OFC397_sum_out1_11_ (.I(sum_out1[11]),
	.ZN(FE_OFN397_sum_out1_11_));
   CKND3 FE_OFC396_sum_out1_12_ (.I(FE_OFN395_sum_out1_12_),
	.ZN(FE_OFN396_sum_out1_12_));
   CKND3 FE_OFC395_sum_out1_12_ (.I(sum_out1[12]),
	.ZN(FE_OFN395_sum_out1_12_));
   CKND3 FE_OFC394_sum_out1_13_ (.I(FE_OFN393_sum_out1_13_),
	.ZN(FE_OFN394_sum_out1_13_));
   CKND3 FE_OFC393_sum_out1_13_ (.I(sum_out1[13]),
	.ZN(FE_OFN393_sum_out1_13_));
   CKND3 FE_OFC392_sum_out1_14_ (.I(FE_OFN391_sum_out1_14_),
	.ZN(FE_OFN392_sum_out1_14_));
   CKND3 FE_OFC391_sum_out1_14_ (.I(sum_out1[14]),
	.ZN(FE_OFN391_sum_out1_14_));
   CKND3 FE_OFC390_sum_out1_15_ (.I(FE_OFN389_sum_out1_15_),
	.ZN(FE_OFN390_sum_out1_15_));
   CKND3 FE_OFC389_sum_out1_15_ (.I(sum_out1[15]),
	.ZN(FE_OFN389_sum_out1_15_));
   CKND3 FE_OFC388_sum_out1_16_ (.I(FE_OFN387_sum_out1_16_),
	.ZN(FE_OFN388_sum_out1_16_));
   CKND3 FE_OFC387_sum_out1_16_ (.I(sum_out1[16]),
	.ZN(FE_OFN387_sum_out1_16_));
   CKND3 FE_OFC386_sum_out1_17_ (.I(FE_OFN385_sum_out1_17_),
	.ZN(FE_OFN386_sum_out1_17_));
   CKND3 FE_OFC385_sum_out1_17_ (.I(sum_out1[17]),
	.ZN(FE_OFN385_sum_out1_17_));
   CKND3 FE_OFC384_sum_out1_18_ (.I(FE_OFN383_sum_out1_18_),
	.ZN(FE_OFN384_sum_out1_18_));
   CKND3 FE_OFC383_sum_out1_18_ (.I(sum_out1[18]),
	.ZN(FE_OFN383_sum_out1_18_));
   CKND3 FE_OFC382_sum_out1_19_ (.I(FE_OFN381_sum_out1_19_),
	.ZN(FE_OFN382_sum_out1_19_));
   CKND3 FE_OFC381_sum_out1_19_ (.I(sum_out1[19]),
	.ZN(FE_OFN381_sum_out1_19_));
   CKND3 FE_OFC380_sum_out1_20_ (.I(FE_OFN379_sum_out1_20_),
	.ZN(FE_OFN380_sum_out1_20_));
   CKND3 FE_OFC379_sum_out1_20_ (.I(sum_out1[20]),
	.ZN(FE_OFN379_sum_out1_20_));
   CKND3 FE_OFC378_sum_out1_21_ (.I(FE_OFN377_sum_out1_21_),
	.ZN(FE_OFN378_sum_out1_21_));
   CKND3 FE_OFC377_sum_out1_21_ (.I(sum_out1[21]),
	.ZN(FE_OFN377_sum_out1_21_));
   CKND2 FE_OFC376_sum_out1_22_ (.I(FE_OFN375_sum_out1_22_),
	.ZN(FE_OFN376_sum_out1_22_));
   CKND2 FE_OFC375_sum_out1_22_ (.I(FE_OFN374_sum_out1_22_),
	.ZN(FE_OFN375_sum_out1_22_));
   CKBD3 FE_OFC374_sum_out1_22_ (.I(sum_out1[22]),
	.Z(FE_OFN374_sum_out1_22_));
   CKND3 FE_OFC373_sum_out1_23_ (.I(FE_OFN372_sum_out1_23_),
	.ZN(FE_OFN373_sum_out1_23_));
   CKND3 FE_OFC372_sum_out1_23_ (.I(sum_out1[23]),
	.ZN(FE_OFN372_sum_out1_23_));
   CKND3 FE_OFC371_sum_out2_0_ (.I(FE_OFN370_sum_out2_0_),
	.ZN(FE_OFN371_sum_out2_0_));
   CKND3 FE_OFC370_sum_out2_0_ (.I(sum_out2[0]),
	.ZN(FE_OFN370_sum_out2_0_));
   CKND3 FE_OFC369_sum_out2_1_ (.I(FE_OFN368_sum_out2_1_),
	.ZN(FE_OFN369_sum_out2_1_));
   CKND3 FE_OFC368_sum_out2_1_ (.I(sum_out2[1]),
	.ZN(FE_OFN368_sum_out2_1_));
   CKND3 FE_OFC367_sum_out2_2_ (.I(FE_OFN366_sum_out2_2_),
	.ZN(FE_OFN367_sum_out2_2_));
   CKND3 FE_OFC366_sum_out2_2_ (.I(sum_out2[2]),
	.ZN(FE_OFN366_sum_out2_2_));
   CKND3 FE_OFC365_sum_out2_3_ (.I(FE_OFN364_sum_out2_3_),
	.ZN(FE_OFN365_sum_out2_3_));
   CKND3 FE_OFC364_sum_out2_3_ (.I(sum_out2[3]),
	.ZN(FE_OFN364_sum_out2_3_));
   CKND3 FE_OFC363_sum_out2_4_ (.I(FE_OFN362_sum_out2_4_),
	.ZN(FE_OFN363_sum_out2_4_));
   CKND4 FE_OFC362_sum_out2_4_ (.I(sum_out2[4]),
	.ZN(FE_OFN362_sum_out2_4_));
   CKND3 FE_OFC361_sum_out2_5_ (.I(FE_OFN360_sum_out2_5_),
	.ZN(FE_OFN361_sum_out2_5_));
   CKND3 FE_OFC360_sum_out2_5_ (.I(sum_out2[5]),
	.ZN(FE_OFN360_sum_out2_5_));
   CKND3 FE_OFC359_sum_out2_6_ (.I(FE_OFN358_sum_out2_6_),
	.ZN(FE_OFN359_sum_out2_6_));
   CKND4 FE_OFC358_sum_out2_6_ (.I(sum_out2[6]),
	.ZN(FE_OFN358_sum_out2_6_));
   CKND3 FE_OFC357_sum_out2_7_ (.I(FE_OFN356_sum_out2_7_),
	.ZN(FE_OFN357_sum_out2_7_));
   CKND3 FE_OFC356_sum_out2_7_ (.I(sum_out2[7]),
	.ZN(FE_OFN356_sum_out2_7_));
   CKND3 FE_OFC355_sum_out2_8_ (.I(FE_OFN354_sum_out2_8_),
	.ZN(FE_OFN355_sum_out2_8_));
   CKND3 FE_OFC354_sum_out2_8_ (.I(sum_out2[8]),
	.ZN(FE_OFN354_sum_out2_8_));
   CKND3 FE_OFC353_sum_out2_9_ (.I(FE_OFN352_sum_out2_9_),
	.ZN(FE_OFN353_sum_out2_9_));
   CKND3 FE_OFC352_sum_out2_9_ (.I(sum_out2[9]),
	.ZN(FE_OFN352_sum_out2_9_));
   CKND3 FE_OFC351_sum_out2_10_ (.I(FE_OFN350_sum_out2_10_),
	.ZN(FE_OFN351_sum_out2_10_));
   CKND3 FE_OFC350_sum_out2_10_ (.I(sum_out2[10]),
	.ZN(FE_OFN350_sum_out2_10_));
   CKND3 FE_OFC349_sum_out2_11_ (.I(FE_OFN348_sum_out2_11_),
	.ZN(FE_OFN349_sum_out2_11_));
   CKND3 FE_OFC348_sum_out2_11_ (.I(sum_out2[11]),
	.ZN(FE_OFN348_sum_out2_11_));
   CKND3 FE_OFC347_sum_out2_12_ (.I(FE_OFN346_sum_out2_12_),
	.ZN(FE_OFN347_sum_out2_12_));
   CKND3 FE_OFC346_sum_out2_12_ (.I(sum_out2[12]),
	.ZN(FE_OFN346_sum_out2_12_));
   CKND3 FE_OFC345_sum_out2_13_ (.I(FE_OFN344_sum_out2_13_),
	.ZN(FE_OFN345_sum_out2_13_));
   CKND4 FE_OFC344_sum_out2_13_ (.I(sum_out2[13]),
	.ZN(FE_OFN344_sum_out2_13_));
   CKND3 FE_OFC343_sum_out2_14_ (.I(FE_OFN342_sum_out2_14_),
	.ZN(FE_OFN343_sum_out2_14_));
   CKND4 FE_OFC342_sum_out2_14_ (.I(sum_out2[14]),
	.ZN(FE_OFN342_sum_out2_14_));
   CKND3 FE_OFC341_sum_out2_15_ (.I(FE_OFN340_sum_out2_15_),
	.ZN(FE_OFN341_sum_out2_15_));
   CKND4 FE_OFC340_sum_out2_15_ (.I(sum_out2[15]),
	.ZN(FE_OFN340_sum_out2_15_));
   CKND3 FE_OFC339_sum_out2_16_ (.I(FE_OFN338_sum_out2_16_),
	.ZN(FE_OFN339_sum_out2_16_));
   CKND3 FE_OFC338_sum_out2_16_ (.I(sum_out2[16]),
	.ZN(FE_OFN338_sum_out2_16_));
   CKND3 FE_OFC337_sum_out2_17_ (.I(FE_OFN336_sum_out2_17_),
	.ZN(FE_OFN337_sum_out2_17_));
   CKND3 FE_OFC336_sum_out2_17_ (.I(sum_out2[17]),
	.ZN(FE_OFN336_sum_out2_17_));
   CKND3 FE_OFC335_sum_out2_18_ (.I(FE_OFN334_sum_out2_18_),
	.ZN(FE_OFN335_sum_out2_18_));
   CKND3 FE_OFC334_sum_out2_18_ (.I(sum_out2[18]),
	.ZN(FE_OFN334_sum_out2_18_));
   CKND3 FE_OFC333_sum_out2_19_ (.I(FE_OFN332_sum_out2_19_),
	.ZN(FE_OFN333_sum_out2_19_));
   CKND3 FE_OFC332_sum_out2_19_ (.I(sum_out2[19]),
	.ZN(FE_OFN332_sum_out2_19_));
   CKND3 FE_OFC331_sum_out2_20_ (.I(FE_OFN330_sum_out2_20_),
	.ZN(FE_OFN331_sum_out2_20_));
   CKND3 FE_OFC330_sum_out2_20_ (.I(sum_out2[20]),
	.ZN(FE_OFN330_sum_out2_20_));
   CKND3 FE_OFC329_sum_out2_21_ (.I(FE_OFN328_sum_out2_21_),
	.ZN(FE_OFN329_sum_out2_21_));
   CKND4 FE_OFC328_sum_out2_21_ (.I(sum_out2[21]),
	.ZN(FE_OFN328_sum_out2_21_));
   CKND3 FE_OFC327_sum_out2_22_ (.I(FE_OFN326_sum_out2_22_),
	.ZN(FE_OFN327_sum_out2_22_));
   CKND4 FE_OFC326_sum_out2_22_ (.I(sum_out2[22]),
	.ZN(FE_OFN326_sum_out2_22_));
   CKND3 FE_OFC325_sum_out2_23_ (.I(FE_OFN324_sum_out2_23_),
	.ZN(FE_OFN325_sum_out2_23_));
   CKND3 FE_OFC324_sum_out2_23_ (.I(sum_out2[23]),
	.ZN(FE_OFN324_sum_out2_23_));
   BUFFD1 FE_OFC323_out2_0_ (.I(FE_OFN322_out2_0_),
	.Z(out2[0]));
   BUFFD1 FE_OFC321_out2_1_ (.I(FE_OFN320_out2_1_),
	.Z(out2[1]));
   CKBD0 FE_OFC319_out2_2_ (.I(FE_OFN318_out2_2_),
	.Z(out2[2]));
   CKBD0 FE_OFC317_out2_3_ (.I(FE_OFN316_out2_3_),
	.Z(out2[3]));
   BUFFD1 FE_OFC315_out2_4_ (.I(FE_OFN314_out2_4_),
	.Z(out2[4]));
   BUFFD1 FE_OFC313_out2_5_ (.I(FE_OFN312_out2_5_),
	.Z(out2[5]));
   CKBD0 FE_OFC311_out2_6_ (.I(FE_OFN310_out2_6_),
	.Z(out2[6]));
   BUFFD1 FE_OFC309_out2_7_ (.I(FE_OFN308_out2_7_),
	.Z(out2[7]));
   CKBD0 FE_OFC307_out2_8_ (.I(FE_OFN306_out2_8_),
	.Z(out2[8]));
   CKBD0 FE_OFC305_out2_9_ (.I(FE_OFN304_out2_9_),
	.Z(out2[9]));
   BUFFD1 FE_OFC303_out2_10_ (.I(FE_OFN302_out2_10_),
	.Z(out2[10]));
   BUFFD1 FE_OFC301_out2_11_ (.I(FE_OFN300_out2_11_),
	.Z(out2[11]));
   CKBD0 FE_OFC299_out2_12_ (.I(FE_OFN298_out2_12_),
	.Z(out2[12]));
   CKBD0 FE_OFC297_out2_13_ (.I(FE_OFN296_out2_13_),
	.Z(out2[13]));
   CKBD0 FE_OFC295_out2_14_ (.I(FE_OFN294_out2_14_),
	.Z(out2[14]));
   CKBD0 FE_OFC293_out2_15_ (.I(FE_OFN292_out2_15_),
	.Z(out2[15]));
   BUFFD1 FE_OFC291_out2_16_ (.I(FE_OFN290_out2_16_),
	.Z(out2[16]));
   BUFFD1 FE_OFC289_out2_17_ (.I(FE_OFN288_out2_17_),
	.Z(out2[17]));
   CKBD0 FE_OFC287_out2_18_ (.I(FE_OFN286_out2_18_),
	.Z(out2[18]));
   CKBD0 FE_OFC285_out2_19_ (.I(FE_OFN284_out2_19_),
	.Z(out2[19]));
   CKBD0 FE_OFC283_out2_20_ (.I(FE_OFN282_out2_20_),
	.Z(out2[20]));
   CKBD0 FE_OFC281_out2_21_ (.I(FE_OFN280_out2_21_),
	.Z(out2[21]));
   CKBD0 FE_OFC279_out2_22_ (.I(FE_OFN278_out2_22_),
	.Z(out2[22]));
   BUFFD1 FE_OFC277_out2_23_ (.I(FE_OFN276_out2_23_),
	.Z(out2[23]));
   CKBD0 FE_OFC275_out2_24_ (.I(FE_OFN274_out2_24_),
	.Z(out2[24]));
   CKBD0 FE_OFC273_out2_25_ (.I(FE_OFN272_out2_25_),
	.Z(out2[25]));
   CKBD0 FE_OFC271_out2_26_ (.I(FE_OFN270_out2_26_),
	.Z(out2[26]));
   CKBD0 FE_OFC269_out2_27_ (.I(FE_OFN268_out2_27_),
	.Z(out2[27]));
   CKBD0 FE_OFC267_out2_28_ (.I(FE_OFN266_out2_28_),
	.Z(out2[28]));
   CKBD0 FE_OFC265_out2_29_ (.I(FE_OFN264_out2_29_),
	.Z(out2[29]));
   CKBD0 FE_OFC263_out2_30_ (.I(FE_OFN262_out2_30_),
	.Z(out2[30]));
   CKBD0 FE_OFC261_out2_31_ (.I(FE_OFN260_out2_31_),
	.Z(out2[31]));
   CKBD0 FE_OFC259_out2_32_ (.I(FE_OFN258_out2_32_),
	.Z(out2[32]));
   CKBD0 FE_OFC257_out2_33_ (.I(FE_OFN256_out2_33_),
	.Z(out2[33]));
   CKBD0 FE_OFC255_out2_34_ (.I(FE_OFN254_out2_34_),
	.Z(out2[34]));
   CKBD0 FE_OFC253_out2_35_ (.I(FE_OFN252_out2_35_),
	.Z(out2[35]));
   CKBD0 FE_OFC251_out2_36_ (.I(FE_OFN250_out2_36_),
	.Z(out2[36]));
   CKBD0 FE_OFC249_out2_37_ (.I(FE_OFN248_out2_37_),
	.Z(out2[37]));
   CKBD0 FE_OFC247_out2_38_ (.I(FE_OFN246_out2_38_),
	.Z(out2[38]));
   CKBD0 FE_OFC245_out2_39_ (.I(FE_OFN244_out2_39_),
	.Z(out2[39]));
   CKBD0 FE_OFC243_out2_40_ (.I(FE_OFN242_out2_40_),
	.Z(out2[40]));
   CKBD0 FE_OFC241_out2_41_ (.I(FE_OFN240_out2_41_),
	.Z(out2[41]));
   CKBD0 FE_OFC239_out2_42_ (.I(FE_OFN238_out2_42_),
	.Z(out2[42]));
   CKBD0 FE_OFC237_out2_43_ (.I(FE_OFN236_out2_43_),
	.Z(out2[43]));
   CKBD0 FE_OFC235_out2_44_ (.I(FE_OFN234_out2_44_),
	.Z(out2[44]));
   CKBD0 FE_OFC233_out2_45_ (.I(FE_OFN232_out2_45_),
	.Z(out2[45]));
   CKBD0 FE_OFC231_out2_46_ (.I(FE_OFN230_out2_46_),
	.Z(out2[46]));
   CKBD0 FE_OFC229_out2_47_ (.I(FE_OFN228_out2_47_),
	.Z(out2[47]));
   CKBD0 FE_OFC227_out2_48_ (.I(FE_OFN226_out2_48_),
	.Z(out2[48]));
   CKBD0 FE_OFC225_out2_49_ (.I(FE_OFN224_out2_49_),
	.Z(out2[49]));
   CKBD0 FE_OFC223_out2_50_ (.I(FE_OFN222_out2_50_),
	.Z(out2[50]));
   CKBD0 FE_OFC221_out2_51_ (.I(FE_OFN220_out2_51_),
	.Z(out2[51]));
   CKBD0 FE_OFC219_out2_52_ (.I(FE_OFN218_out2_52_),
	.Z(out2[52]));
   CKBD0 FE_OFC217_out2_53_ (.I(FE_OFN216_out2_53_),
	.Z(out2[53]));
   CKBD0 FE_OFC215_out2_54_ (.I(FE_OFN214_out2_54_),
	.Z(out2[54]));
   CKBD0 FE_OFC213_out2_55_ (.I(FE_OFN212_out2_55_),
	.Z(out2[55]));
   CKBD0 FE_OFC211_out2_56_ (.I(FE_OFN210_out2_56_),
	.Z(out2[56]));
   CKBD0 FE_OFC209_out2_57_ (.I(FE_OFN208_out2_57_),
	.Z(out2[57]));
   CKBD0 FE_OFC207_out2_58_ (.I(FE_OFN206_out2_58_),
	.Z(out2[58]));
   CKBD0 FE_OFC205_out2_59_ (.I(FE_OFN204_out2_59_),
	.Z(out2[59]));
   CKBD0 FE_OFC203_out2_60_ (.I(FE_OFN202_out2_60_),
	.Z(out2[60]));
   CKBD0 FE_OFC201_out2_61_ (.I(FE_OFN200_out2_61_),
	.Z(out2[61]));
   CKBD0 FE_OFC199_out2_62_ (.I(FE_OFN198_out2_62_),
	.Z(out2[62]));
   CKBD0 FE_OFC197_out2_63_ (.I(FE_OFN196_out2_63_),
	.Z(out2[63]));
   CKBD0 FE_OFC195_out2_64_ (.I(FE_OFN194_out2_64_),
	.Z(out2[64]));
   CKBD0 FE_OFC193_out2_65_ (.I(FE_OFN192_out2_65_),
	.Z(out2[65]));
   CKBD0 FE_OFC191_out2_66_ (.I(FE_OFN190_out2_66_),
	.Z(out2[66]));
   CKBD0 FE_OFC189_out2_67_ (.I(FE_OFN188_out2_67_),
	.Z(out2[67]));
   CKBD0 FE_OFC187_out2_68_ (.I(FE_OFN186_out2_68_),
	.Z(out2[68]));
   CKBD0 FE_OFC185_out2_69_ (.I(FE_OFN184_out2_69_),
	.Z(out2[69]));
   CKBD0 FE_OFC183_out2_70_ (.I(FE_OFN182_out2_70_),
	.Z(out2[70]));
   CKBD0 FE_OFC181_out2_71_ (.I(FE_OFN180_out2_71_),
	.Z(out2[71]));
   CKBD0 FE_OFC179_out2_72_ (.I(FE_OFN178_out2_72_),
	.Z(out2[72]));
   CKBD0 FE_OFC177_out2_73_ (.I(FE_OFN176_out2_73_),
	.Z(out2[73]));
   CKBD0 FE_OFC175_out2_74_ (.I(FE_OFN174_out2_74_),
	.Z(out2[74]));
   CKBD0 FE_OFC173_out2_75_ (.I(FE_OFN172_out2_75_),
	.Z(out2[75]));
   CKBD0 FE_OFC171_out2_76_ (.I(FE_OFN170_out2_76_),
	.Z(out2[76]));
   CKBD0 FE_OFC169_out2_77_ (.I(FE_OFN168_out2_77_),
	.Z(out2[77]));
   CKBD0 FE_OFC167_out2_78_ (.I(FE_OFN166_out2_78_),
	.Z(out2[78]));
   CKBD0 FE_OFC165_out2_79_ (.I(FE_OFN164_out2_79_),
	.Z(out2[79]));
   CKBD0 FE_OFC163_out2_80_ (.I(FE_OFN162_out2_80_),
	.Z(out2[80]));
   CKBD0 FE_OFC161_out2_81_ (.I(FE_OFN160_out2_81_),
	.Z(out2[81]));
   CKBD0 FE_OFC159_out2_83_ (.I(FE_OFN158_out2_83_),
	.Z(out2[83]));
   CKBD0 FE_OFC157_out2_84_ (.I(FE_OFN156_out2_84_),
	.Z(out2[84]));
   CKBD0 FE_OFC155_out2_85_ (.I(FE_OFN154_out2_85_),
	.Z(out2[85]));
   CKBD0 FE_OFC153_out2_87_ (.I(FE_OFN152_out2_87_),
	.Z(out2[87]));
   CKBD0 FE_OFC151_out2_89_ (.I(FE_OFN150_out2_89_),
	.Z(out2[89]));
   CKBD0 FE_OFC149_out2_126_ (.I(FE_OFN148_out2_126_),
	.Z(out2[126]));
   CKBD0 FE_OFC147_out1_0_ (.I(FE_OFN146_out1_0_),
	.Z(out1[0]));
   CKBD0 FE_OFC145_out1_1_ (.I(FE_OFN144_out1_1_),
	.Z(out1[1]));
   CKBD0 FE_OFC143_out1_2_ (.I(FE_OFN142_out1_2_),
	.Z(out1[2]));
   CKBD0 FE_OFC141_out1_3_ (.I(FE_OFN140_out1_3_),
	.Z(out1[3]));
   CKBD0 FE_OFC139_out1_4_ (.I(FE_OFN138_out1_4_),
	.Z(out1[4]));
   CKBD0 FE_OFC137_out1_5_ (.I(FE_OFN136_out1_5_),
	.Z(out1[5]));
   CKBD0 FE_OFC135_out1_6_ (.I(FE_OFN134_out1_6_),
	.Z(out1[6]));
   CKBD0 FE_OFC133_out1_7_ (.I(FE_OFN132_out1_7_),
	.Z(out1[7]));
   CKBD0 FE_OFC131_out1_8_ (.I(FE_OFN130_out1_8_),
	.Z(out1[8]));
   CKBD0 FE_OFC129_out1_9_ (.I(FE_OFN128_out1_9_),
	.Z(out1[9]));
   CKBD0 FE_OFC127_out1_10_ (.I(FE_OFN126_out1_10_),
	.Z(out1[10]));
   CKBD0 FE_OFC125_out1_11_ (.I(FE_OFN124_out1_11_),
	.Z(out1[11]));
   CKBD0 FE_OFC123_out1_12_ (.I(FE_OFN122_out1_12_),
	.Z(out1[12]));
   CKBD0 FE_OFC121_out1_13_ (.I(FE_OFN120_out1_13_),
	.Z(out1[13]));
   CKBD0 FE_OFC119_out1_14_ (.I(FE_OFN118_out1_14_),
	.Z(out1[14]));
   CKBD0 FE_OFC117_out1_15_ (.I(FE_OFN116_out1_15_),
	.Z(out1[15]));
   CKBD0 FE_OFC115_out1_16_ (.I(FE_OFN114_out1_16_),
	.Z(out1[16]));
   CKBD0 FE_OFC113_out1_17_ (.I(FE_OFN112_out1_17_),
	.Z(out1[17]));
   CKBD0 FE_OFC111_out1_18_ (.I(FE_OFN110_out1_18_),
	.Z(out1[18]));
   CKBD0 FE_OFC109_out1_19_ (.I(FE_OFN108_out1_19_),
	.Z(out1[19]));
   CKBD0 FE_OFC107_out1_20_ (.I(FE_OFN106_out1_20_),
	.Z(out1[20]));
   CKBD0 FE_OFC105_out1_21_ (.I(FE_OFN104_out1_21_),
	.Z(out1[21]));
   CKBD0 FE_OFC103_out1_22_ (.I(FE_OFN102_out1_22_),
	.Z(out1[22]));
   CKBD0 FE_OFC101_out1_23_ (.I(FE_OFN100_out1_23_),
	.Z(out1[23]));
   CKBD0 FE_OFC99_out1_24_ (.I(FE_OFN98_out1_24_),
	.Z(out1[24]));
   CKBD0 FE_OFC97_out1_25_ (.I(FE_OFN96_out1_25_),
	.Z(out1[25]));
   CKBD0 FE_OFC95_out1_26_ (.I(FE_OFN94_out1_26_),
	.Z(out1[26]));
   CKBD0 FE_OFC93_out1_27_ (.I(FE_OFN92_out1_27_),
	.Z(out1[27]));
   CKBD0 FE_OFC91_out1_28_ (.I(FE_OFN90_out1_28_),
	.Z(out1[28]));
   CKBD0 FE_OFC89_out1_31_ (.I(FE_OFN88_out1_31_),
	.Z(out1[31]));
   CKBD0 FE_OFC87_out1_32_ (.I(FE_OFN86_out1_32_),
	.Z(out1[32]));
   CKBD0 FE_OFC85_out1_39_ (.I(FE_OFN84_out1_39_),
	.Z(out1[39]));
   CKBD0 FE_OFC83_out1_40_ (.I(FE_OFN82_out1_40_),
	.Z(out1[40]));
   CKBD0 FE_OFC81_out1_43_ (.I(FE_OFN80_out1_43_),
	.Z(out1[43]));
   CKBD0 FE_OFC79_out1_45_ (.I(FE_OFN78_out1_45_),
	.Z(out1[45]));
   CKBD0 FE_OFC77_out1_46_ (.I(FE_OFN76_out1_46_),
	.Z(out1[46]));
   CKBD0 FE_OFC75_out1_48_ (.I(FE_OFN74_out1_48_),
	.Z(out1[48]));
   CKBD0 FE_OFC73_out1_51_ (.I(FE_OFN72_out1_51_),
	.Z(out1[51]));
   CKBD0 FE_OFC71_out1_56_ (.I(FE_OFN70_out1_56_),
	.Z(out1[56]));
   CKBD0 FE_OFC69_out1_64_ (.I(FE_OFN68_out1_64_),
	.Z(out1[64]));
   CKBD0 FE_OFC67_out1_65_ (.I(FE_OFN66_out1_65_),
	.Z(out1[65]));
   CKBD0 FE_OFC65_out1_66_ (.I(FE_OFN64_out1_66_),
	.Z(out1[66]));
   CKBD0 FE_OFC63_out1_67_ (.I(FE_OFN62_out1_67_),
	.Z(out1[67]));
   CKBD0 FE_OFC61_out1_68_ (.I(FE_OFN60_out1_68_),
	.Z(out1[68]));
   CKBD0 FE_OFC59_out1_70_ (.I(FE_OFN58_out1_70_),
	.Z(out1[70]));
   CKBD0 FE_OFC57_out1_76_ (.I(FE_OFN56_out1_76_),
	.Z(out1[76]));
   CKBD0 FE_OFC55_out1_77_ (.I(FE_OFN54_out1_77_),
	.Z(out1[77]));
   CKBD0 FE_OFC53_out1_78_ (.I(FE_OFN52_out1_78_),
	.Z(out1[78]));
   CKBD0 FE_OFC51_out1_79_ (.I(FE_OFN50_out1_79_),
	.Z(out1[79]));
   CKBD0 FE_OFC49_out1_80_ (.I(FE_OFN48_out1_80_),
	.Z(out1[80]));
   CKBD0 FE_OFC47_out1_81_ (.I(FE_OFN46_out1_81_),
	.Z(out1[81]));
   CKBD0 FE_OFC45_out1_83_ (.I(FE_OFN44_out1_83_),
	.Z(out1[83]));
   CKBD0 FE_OFC43_out1_84_ (.I(FE_OFN42_out1_84_),
	.Z(out1[84]));
   CKBD0 FE_OFC41_out1_87_ (.I(FE_OFN40_out1_87_),
	.Z(out1[87]));
   CKBD0 FE_OFC39_out1_89_ (.I(FE_OFN38_out1_89_),
	.Z(out1[89]));
   CKBD0 FE_OFC37_out1_90_ (.I(FE_OFN36_out1_90_),
	.Z(out1[90]));
   CKBD0 FE_OFC35_out1_91_ (.I(FE_OFN34_out1_91_),
	.Z(out1[91]));
   CKBD0 FE_OFC33_out1_92_ (.I(FE_OFN32_out1_92_),
	.Z(out1[92]));
   CKBD0 FE_OFC31_out1_93_ (.I(FE_OFN30_out1_93_),
	.Z(out1[93]));
   CKBD0 FE_OFC29_out1_94_ (.I(FE_OFN28_out1_94_),
	.Z(out1[94]));
   CKBD0 FE_OFC27_out1_95_ (.I(FE_OFN26_out1_95_),
	.Z(out1[95]));
   CKBD0 FE_OFC25_out1_96_ (.I(FE_OFN24_out1_96_),
	.Z(out1[96]));
   CKBD0 FE_OFC23_out1_97_ (.I(FE_OFN22_out1_97_),
	.Z(out1[97]));
   CKBD0 FE_OFC21_out1_98_ (.I(FE_OFN20_out1_98_),
	.Z(out1[98]));
   CKBD0 FE_OFC19_out1_99_ (.I(FE_OFN18_out1_99_),
	.Z(out1[99]));
   CKBD0 FE_OFC17_out1_100_ (.I(FE_OFN16_out1_100_),
	.Z(out1[100]));
   CKBD0 FE_OFC15_out1_101_ (.I(FE_OFN14_out1_101_),
	.Z(out1[101]));
   CKBD0 FE_OFC13_out1_106_ (.I(FE_OFN12_out1_106_),
	.Z(out1[106]));
   CKBD0 FE_OFC11_out1_112_ (.I(FE_OFN10_out1_112_),
	.Z(out1[112]));
   CKBD0 FE_OFC9_out1_125_ (.I(FE_OFN8_out1_125_),
	.Z(out1[125]));
   CKBD0 FE_OFC7_out1_126_ (.I(FE_OFN6_out1_126_),
	.Z(out1[126]));
   CKBD0 FE_OFC5_out1_127_ (.I(FE_OFN4_out1_127_),
	.Z(out1[127]));
   CKND2 FE_OFC3_inst2_18_ (.I(FE_OFN2_inst2_18_),
	.ZN(FE_OFN3_inst2_18_));
   CKND2 FE_OFC2_inst2_18_ (.I(inst2[18]),
	.ZN(FE_OFN2_inst2_18_));
   CKND2 FE_OFC1_inst1_18_ (.I(FE_OFN0_inst1_18_),
	.ZN(FE_OFN1_inst1_18_));
   CKND2 FE_OFC0_inst1_18_ (.I(inst1[18]),
	.ZN(FE_OFN0_inst1_18_));
   core core_instance1 (.reset(reset),
	.inst(inst1),
	.out({ out1[159],
		out1[158],
		out1[157],
		out1[156],
		out1[155],
		out1[154],
		out1[153],
		out1[152],
		out1[151],
		out1[150],
		out1[149],
		out1[148],
		out1[147],
		out1[146],
		out1[145],
		out1[144],
		out1[143],
		out1[142],
		out1[141],
		out1[140],
		out1[139],
		out1[138],
		out1[137],
		out1[136],
		out1[135],
		out1[134],
		out1[133],
		out1[132],
		out1[131],
		out1[130],
		out1[129],
		out1[128],
		FE_OFN4_out1_127_,
		FE_OFN6_out1_126_,
		FE_OFN8_out1_125_,
		FE_OFN423_out1_124_,
		out1[123],
		out1[122],
		out1[121],
		out1[120],
		out1[119],
		out1[118],
		out1[117],
		out1[116],
		out1[115],
		out1[114],
		out1[113],
		FE_OFN10_out1_112_,
		out1[111],
		out1[110],
		FE_OFN425_out1_109_,
		out1[108],
		out1[107],
		FE_OFN12_out1_106_,
		out1[105],
		out1[104],
		out1[103],
		out1[102],
		FE_OFN14_out1_101_,
		FE_OFN16_out1_100_,
		FE_OFN18_out1_99_,
		FE_OFN20_out1_98_,
		FE_OFN22_out1_97_,
		FE_OFN24_out1_96_,
		FE_OFN26_out1_95_,
		FE_OFN28_out1_94_,
		FE_OFN30_out1_93_,
		FE_OFN32_out1_92_,
		FE_OFN34_out1_91_,
		FE_OFN36_out1_90_,
		FE_OFN38_out1_89_,
		out1[88],
		FE_OFN40_out1_87_,
		out1[86],
		out1[85],
		FE_OFN42_out1_84_,
		FE_OFN44_out1_83_,
		out1[82],
		FE_OFN46_out1_81_,
		FE_OFN48_out1_80_,
		FE_OFN50_out1_79_,
		FE_OFN52_out1_78_,
		FE_OFN54_out1_77_,
		FE_OFN56_out1_76_,
		out1[75],
		out1[74],
		out1[73],
		out1[72],
		out1[71],
		FE_OFN58_out1_70_,
		out1[69],
		FE_OFN60_out1_68_,
		FE_OFN62_out1_67_,
		FE_OFN64_out1_66_,
		FE_OFN66_out1_65_,
		FE_OFN68_out1_64_,
		out1[63],
		out1[62],
		out1[61],
		out1[60],
		out1[59],
		out1[58],
		out1[57],
		FE_OFN70_out1_56_,
		out1[55],
		out1[54],
		out1[53],
		out1[52],
		FE_OFN72_out1_51_,
		out1[50],
		out1[49],
		FE_OFN74_out1_48_,
		out1[47],
		FE_OFN76_out1_46_,
		FE_OFN78_out1_45_,
		FE_OFN429_out1_44_,
		FE_OFN80_out1_43_,
		out1[42],
		out1[41],
		FE_OFN82_out1_40_,
		FE_OFN84_out1_39_,
		out1[38],
		out1[37],
		out1[36],
		out1[35],
		out1[34],
		out1[33],
		FE_OFN86_out1_32_,
		FE_OFN88_out1_31_,
		out1[30],
		out1[29],
		FE_OFN90_out1_28_,
		FE_OFN92_out1_27_,
		FE_OFN94_out1_26_,
		FE_OFN96_out1_25_,
		FE_OFN98_out1_24_,
		FE_OFN100_out1_23_,
		FE_OFN102_out1_22_,
		FE_OFN104_out1_21_,
		FE_OFN106_out1_20_,
		FE_OFN108_out1_19_,
		FE_OFN110_out1_18_,
		FE_OFN112_out1_17_,
		FE_OFN114_out1_16_,
		FE_OFN116_out1_15_,
		FE_OFN118_out1_14_,
		FE_OFN120_out1_13_,
		FE_OFN122_out1_12_,
		FE_OFN124_out1_11_,
		FE_OFN126_out1_10_,
		FE_OFN128_out1_9_,
		FE_OFN130_out1_8_,
		FE_OFN132_out1_7_,
		FE_OFN134_out1_6_,
		FE_OFN136_out1_5_,
		FE_OFN138_out1_4_,
		FE_OFN140_out1_3_,
		FE_OFN142_out1_2_,
		FE_OFN144_out1_1_,
		FE_OFN146_out1_0_ }),
	.mem_in(mem_in1),
	.sum_out(sum_out1),
	.fifo_ext_rd(FE_OFN3_inst2_18_),
	.sum_in({ FE_OFN325_sum_out2_23_,
		FE_OFN327_sum_out2_22_,
		FE_OFN329_sum_out2_21_,
		FE_OFN331_sum_out2_20_,
		FE_OFN333_sum_out2_19_,
		FE_OFN335_sum_out2_18_,
		FE_OFN337_sum_out2_17_,
		FE_OFN339_sum_out2_16_,
		FE_OFN341_sum_out2_15_,
		FE_OFN343_sum_out2_14_,
		FE_OFN345_sum_out2_13_,
		FE_OFN347_sum_out2_12_,
		FE_OFN349_sum_out2_11_,
		FE_OFN351_sum_out2_10_,
		FE_OFN353_sum_out2_9_,
		FE_OFN355_sum_out2_8_,
		FE_OFN357_sum_out2_7_,
		FE_OFN359_sum_out2_6_,
		FE_OFN361_sum_out2_5_,
		FE_OFN363_sum_out2_4_,
		FE_OFN365_sum_out2_3_,
		FE_OFN367_sum_out2_2_,
		FE_OFN369_sum_out2_1_,
		FE_OFN371_sum_out2_0_ }),
	.clk(CTS_8));
   core core_instance2 (.reset(reset),
	.inst(inst2),
	.out({ out2[159],
		out2[158],
		out2[157],
		out2[156],
		out2[155],
		out2[154],
		out2[153],
		out2[152],
		out2[151],
		out2[150],
		out2[149],
		out2[148],
		out2[147],
		out2[146],
		out2[145],
		out2[144],
		out2[143],
		out2[142],
		out2[141],
		out2[140],
		out2[139],
		out2[138],
		out2[137],
		out2[136],
		out2[135],
		out2[134],
		out2[133],
		out2[132],
		out2[131],
		out2[130],
		out2[129],
		out2[128],
		out2[127],
		FE_OFN148_out2_126_,
		FE_OFN427_out2_125_,
		out2[124],
		out2[123],
		out2[122],
		out2[121],
		out2[120],
		out2[119],
		out2[118],
		out2[117],
		out2[116],
		out2[115],
		out2[114],
		out2[113],
		out2[112],
		out2[111],
		out2[110],
		out2[109],
		out2[108],
		out2[107],
		out2[106],
		out2[105],
		out2[104],
		out2[103],
		out2[102],
		out2[101],
		out2[100],
		out2[99],
		out2[98],
		out2[97],
		out2[96],
		out2[95],
		out2[94],
		out2[93],
		out2[92],
		out2[91],
		out2[90],
		FE_OFN150_out2_89_,
		out2[88],
		FE_OFN152_out2_87_,
		out2[86],
		FE_OFN154_out2_85_,
		FE_OFN156_out2_84_,
		FE_OFN158_out2_83_,
		out2[82],
		FE_OFN160_out2_81_,
		FE_OFN162_out2_80_,
		FE_OFN164_out2_79_,
		FE_OFN166_out2_78_,
		FE_OFN168_out2_77_,
		FE_OFN170_out2_76_,
		FE_OFN172_out2_75_,
		FE_OFN174_out2_74_,
		FE_OFN176_out2_73_,
		FE_OFN178_out2_72_,
		FE_OFN180_out2_71_,
		FE_OFN182_out2_70_,
		FE_OFN184_out2_69_,
		FE_OFN186_out2_68_,
		FE_OFN188_out2_67_,
		FE_OFN190_out2_66_,
		FE_OFN192_out2_65_,
		FE_OFN194_out2_64_,
		FE_OFN196_out2_63_,
		FE_OFN198_out2_62_,
		FE_OFN200_out2_61_,
		FE_OFN202_out2_60_,
		FE_OFN204_out2_59_,
		FE_OFN206_out2_58_,
		FE_OFN208_out2_57_,
		FE_OFN210_out2_56_,
		FE_OFN212_out2_55_,
		FE_OFN214_out2_54_,
		FE_OFN216_out2_53_,
		FE_OFN218_out2_52_,
		FE_OFN220_out2_51_,
		FE_OFN222_out2_50_,
		FE_OFN224_out2_49_,
		FE_OFN226_out2_48_,
		FE_OFN228_out2_47_,
		FE_OFN230_out2_46_,
		FE_OFN232_out2_45_,
		FE_OFN234_out2_44_,
		FE_OFN236_out2_43_,
		FE_OFN238_out2_42_,
		FE_OFN240_out2_41_,
		FE_OFN242_out2_40_,
		FE_OFN244_out2_39_,
		FE_OFN246_out2_38_,
		FE_OFN248_out2_37_,
		FE_OFN250_out2_36_,
		FE_OFN252_out2_35_,
		FE_OFN254_out2_34_,
		FE_OFN256_out2_33_,
		FE_OFN258_out2_32_,
		FE_OFN260_out2_31_,
		FE_OFN262_out2_30_,
		FE_OFN264_out2_29_,
		FE_OFN266_out2_28_,
		FE_OFN268_out2_27_,
		FE_OFN270_out2_26_,
		FE_OFN272_out2_25_,
		FE_OFN274_out2_24_,
		FE_OFN276_out2_23_,
		FE_OFN278_out2_22_,
		FE_OFN280_out2_21_,
		FE_OFN282_out2_20_,
		FE_OFN284_out2_19_,
		FE_OFN286_out2_18_,
		FE_OFN288_out2_17_,
		FE_OFN290_out2_16_,
		FE_OFN292_out2_15_,
		FE_OFN294_out2_14_,
		FE_OFN296_out2_13_,
		FE_OFN298_out2_12_,
		FE_OFN300_out2_11_,
		FE_OFN302_out2_10_,
		FE_OFN304_out2_9_,
		FE_OFN306_out2_8_,
		FE_OFN308_out2_7_,
		FE_OFN310_out2_6_,
		FE_OFN312_out2_5_,
		FE_OFN314_out2_4_,
		FE_OFN316_out2_3_,
		FE_OFN318_out2_2_,
		FE_OFN320_out2_1_,
		FE_OFN322_out2_0_ }),
	.mem_in(mem_in2),
	.sum_out(sum_out2),
	.fifo_ext_rd(FE_OFN1_inst1_18_),
	.sum_in({ FE_OFN373_sum_out1_23_,
		FE_OFN376_sum_out1_22_,
		FE_OFN378_sum_out1_21_,
		FE_OFN380_sum_out1_20_,
		FE_OFN382_sum_out1_19_,
		FE_OFN384_sum_out1_18_,
		FE_OFN386_sum_out1_17_,
		FE_OFN388_sum_out1_16_,
		FE_OFN390_sum_out1_15_,
		FE_OFN392_sum_out1_14_,
		FE_OFN394_sum_out1_13_,
		FE_OFN396_sum_out1_12_,
		FE_OFN398_sum_out1_11_,
		FE_OFN400_sum_out1_10_,
		FE_OFN402_sum_out1_9_,
		FE_OFN404_sum_out1_8_,
		FE_OFN406_sum_out1_7_,
		FE_OFN408_sum_out1_6_,
		FE_OFN410_sum_out1_5_,
		FE_OFN412_sum_out1_4_,
		FE_OFN414_sum_out1_3_,
		FE_OFN416_sum_out1_2_,
		FE_OFN418_sum_out1_1_,
		FE_OFN420_sum_out1_0_ }),
	.clk(CTS_7));
endmodule

